### PR TITLE
[WIP] Convert webpage to USWDS template

### PR DESCRIPTION
**Pull request by shawndwells**
It's been on the to-do for some time... but someone had to do it. Here's a first stab.

Live copy @ https://shawndwells.github.io/opencontrol-website/

-- edit --
Known issues:

- [ ] - The community page has all companies listed on the current webpage. Created a community section that names individuals but only included a few people. Thought was not everyone may want to be listed, and having a few seems sufficient for initial release. We can incrementally add everyone :)
- [ ] - Requires coordination of switching over the CNAME alias. Need to find out who owns this.

### CODE REVIEW

**Comment by shawndwells** [comment]
Few screen shots:

image


image

image

**Comment by afeld** [comment]
Amazing! Looks great - nice work. Only thing I would say is a blocker is getting the OpenControl logo in there in place of the 18F ones.

**Comment by shawndwells** [comment]
No problem @afeld. Do you know who controls the open-control.org domain name? This would require a CNAME change.

**Comment by shawndwells** [comment]
@afeld logo removed & replaced:

image

-- edit --
also removed from footer:
image

**Comment by shawndwells** [comment]
broadening the ask a little -- @afeld @gregelin @anweiss do y'all know who own the open-control.org domain? This would require a CNAME change. Thanks!

**Comment by afeld** [comment]
I believe it's @joshuamckenty.

**Comment by joshuamckenty** [comment]
Happy to make a change - what’s the request, exactly?

**Comment by afeld** [comment]
@shawndwells How would you feel about us splitting up the design changes from the content changes, so we can address them independently?

**Comment by shawndwells** [comment]
On 4/21/19 6:12 PM, Aidan Feldman wrote:
> @shawndwells <https://github.com/shawndwells> How would you feel about 
> us splitting up the design changes from the content changes, so we can 
> address them independently?


There shouldn't be any content changes, but anything that helps move 
this along! Have been waiting for almost 2 months.

**Comment by afeld** [comment]
Cool, gonna close this one out then. Thanks again for getting this going!

**Pull request closed without merging**
